name: Build FFmpeg Android Libraries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  NDK_VERSION: 25.2.9519653
  BUILD_DIR: build_android
  FFMPEG_VERSION: 6.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86, x86_64]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android NDK
      run: |
        echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${NDK_VERSION}"
        echo "ANDROID_NDK=${ANDROID_HOME}/ndk/${NDK_VERSION}" >> $GITHUB_ENV
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          cmake \
          git \
          libtool \
          pkg-config \
          yasm
    
    - name: Create build directory
      run: mkdir -p ${{ env.BUILD_DIR }}
    
    - name: Configure FFmpeg
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        ../configure \
          --enable-shared \
          --enable-cross-compile \
          --cross-prefix=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/ \
          --target-os=android \
          --arch=${{ matrix.arch }} \
          --sysroot=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --extra-cflags="-fPIC -DANDROID" \
          --disable-static \
          --disable-doc \
          --disable-programs \
          --enable-jni \
          --enable-mediacodec \
          --enable-decoder=h264_mediacodec \
          --prefix=$(pwd)/android/${{ matrix.arch }}
    
    - name: Build FFmpeg
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        make -j$(nproc)
        make install
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-libs-${{ matrix.arch }}
        path: ${{ env.BUILD_DIR }}/android/${{ matrix.arch }}/lib/*.so
        if-no-files-found: error

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.BUILD_DIR }}/android/${{ matrix.arch }}/lib/*.so
        name: FFmpeg Android Libraries ${{ env.FFMPEG_VERSION }}
        tag_name: v${{ env.FFMPEG_VERSION }}-android-${{ matrix.arch }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
