name: Build FFmpeg Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      NDK_VERSION: 26.2.11394342

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android NDK
      run: |
        echo "y" | sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config

    - name: Configure and Build FFmpeg
      run: |
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        export NDK_PATH=$ANDROID_SDK_ROOT/ndk/${{ env.NDK_VERSION }}
        export TOOLCHAIN=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64
        export PATH=$TOOLCHAIN/bin:$PATH
        export SYSROOT=$TOOLCHAIN/sysroot
        export PREFIX=$GITHUB_WORKSPACE/prebuilt/android-arm64/ffmpeg
        export CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang
        export CXX=$TOOLCHAIN/bin/aarch64-linux-android21-clang++
        export CROSS_PREFIX=aarch64-linux-android-
        export AR=$TOOLCHAIN/bin/llvm-ar
        export AS=$CC
        export NM=$TOOLCHAIN/bin/llvm-nm
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export LDFLAGS="-L$TOOLCHAIN/sysroot/usr/lib/aarch64-linux-android/21"
        
        mkdir -p $PREFIX
        
        ./configure \
          --prefix=$PREFIX \
          --cross-prefix=$CROSS_PREFIX \
          --sysroot=$SYSROOT \
          --arch=aarch64 \
          --cpu=armv8-a \
          --cc=$CC \
          --cxx=$CXX \
          --ar=$AR \
          --ranlib=$RANLIB \
          --strip=$STRIP \
          --nm=$NM \
          --target-os=android \
          --enable-cross-compile \
          --enable-shared \
          --disable-static \
          --disable-doc \
          --disable-ffmpeg \
          --disable-ffplay \
          --disable-ffprobe \
          --disable-avdevice \
          --disable-devices \
          --disable-indevs \
          --disable-outdevs \
          --enable-small \
          --enable-jni \
          --enable-mediacodec \
          --enable-decoder=h264_mediacodec \
          --enable-hwaccel=h264_mediacodec \
          --disable-debug \
          --enable-neon \
          --enable-asm || {
            echo "Configure failed. Contents of config.log:"
            cat ffbuild/config.log
            exit 1
          }

        make -j$(nproc)
        make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-arm64
        path: prebuilt/android-arm64/ffmpeg
        if-no-files-found: error
