name: Build FFmpeg Android Libraries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  NDK_VERSION: 25.2.9519653
  BUILD_DIR: build_android
  FFMPEG_VERSION: 6.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: armeabi-v7a
            cpu: armv7-a
            target: armv7a-linux-androideabi
            api: 21
          - arch: arm64-v8a
            cpu: armv8-a
            target: aarch64-linux-android
            api: 21
          - arch: x86
            cpu: i686
            target: i686-linux-android
            api: 21
          - arch: x86_64
            cpu: x86_64
            target: x86_64-linux-android
            api: 21
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android NDK
      run: |
        echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${NDK_VERSION}"
        echo "ANDROID_NDK=${ANDROID_HOME}/ndk/${NDK_VERSION}" >> $GITHUB_ENV
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          cmake \
          git \
          libtool \
          pkg-config \
          yasm
    
    - name: Install gas-preprocessor
      run: |
        curl -L https://github.com/FFmpeg/gas-preprocessor/raw/master/gas-preprocessor.pl -o /usr/local/bin/gas-preprocessor.pl
        chmod +x /usr/local/bin/gas-preprocessor.pl

    - name: Create build directory
      run: mkdir -p ${{ env.BUILD_DIR }}
    
    - name: Configure FFmpeg
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        ../configure \
          --prefix=$(pwd)/android/${{ matrix.arch }} \
          --enable-shared \
          --enable-cross-compile \
          --target-os=android \
          --arch=${{ matrix.cpu }} \
          --cpu=${{ matrix.cpu }} \
          --cc=${{ matrix.target }}${{ matrix.api }}-clang \
          --cxx=${{ matrix.target }}${{ matrix.api }}-clang++ \
          --ld=${{ matrix.target }}${{ matrix.api }}-clang \
          --ar=${{ matrix.target }}-ar \
          --as=gas-preprocessor.pl \
          --strip=${{ matrix.target }}-strip \
          --ranlib=${{ matrix.target }}-ranlib \
          --pkg-config=pkg-config \
          --sysroot=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --extra-cflags="-fPIC -DANDROID -D__ANDROID_API__=${{ matrix.api }}" \
          --extra-ldflags="-L$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/${{ matrix.target }}/${{ matrix.api }}" \
          --disable-static \
          --disable-doc \
          --disable-programs \
          --disable-stripping \
          --enable-jni \
          --enable-mediacodec \
          --enable-decoder=h264_mediacodec \
          --enable-neon
    
    - name: Build FFmpeg
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        make -j$(nproc)
        make install
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-libs-${{ matrix.arch }}
        path: ${{ env.BUILD_DIR }}/android/${{ matrix.arch }}/lib/*.so
        if-no-files-found: error

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.BUILD_DIR }}/android/${{ matrix.arch }}/lib/*.so
        name: FFmpeg Android Libraries ${{ env.FFMPEG_VERSION }}
        tag_name: v${{ env.FFMPEG_VERSION }}-android-${{ matrix.arch }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
