name: Build FFmpeg Android Audio Libraries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  NDK_VERSION: 25.2.9519653
  BUILD_DIR: build_android
  FFMPEG_VERSION: 6.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: arm64-v8a
            target: aarch64-linux-android
            api: 21
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Android NDK
      run: |
        echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${NDK_VERSION}"
        echo "ANDROID_NDK=${ANDROID_HOME}/ndk/${NDK_VERSION}" >> $GITHUB_ENV
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          cmake \
          git \
          libtool \
          pkg-config \
          nasm \
          yasm
    
    - name: Create build directory
      run: mkdir -p ${{ env.BUILD_DIR }}
    
    - name: Configure FFmpeg
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        ../configure \
          --prefix=$(pwd)/android/${{ matrix.arch }} \
          --enable-cross-compile \
          --target-os=android \
          --arch=aarch64 \
          --cpu=armv8-a \
          --cc=${{ matrix.target }}${{ matrix.api }}-clang \
          --cxx=${{ matrix.target }}${{ matrix.api }}-clang++ \
          --strip=llvm-strip \
          --ranlib=llvm-ranlib \
          --ar=llvm-ar \
          --nm=llvm-nm \
          --pkg-config=pkg-config \
          --sysroot=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --extra-cflags="-fPIC -DANDROID -D__ANDROID_API__=${{ matrix.api }}" \
          --enable-shared \
          --enable-pic \
          --enable-jni \
          --enable-version3 \
          --enable-neon \
          --enable-pthreads \
          --disable-static \
          --disable-doc \
          --disable-programs \
          --disable-autodetect \
          --disable-debug \
          --disable-postproc \
          --disable-encoders \
          --disable-muxers \
          --disable-videotoolbox \
          --disable-vaapi \
          --disable-vdpau \
          --disable-audiotoolbox \
          --disable-cuda \
          --disable-cuvid \
          --disable-nvenc \
          --disable-nvdec \
          --disable-v4l2-m2m \
          --disable-outdev=fbdev \
          --disable-indev=fbdev
    
    - name: Build FFmpeg
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        make -j$(nproc)
        make install
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-android-libs-${{ matrix.arch }}
        path: ${{ env.BUILD_DIR }}/android/${{ matrix.arch }}/lib/*.so
        if-no-files-found: error
